// This file was auto-generated by ML.NET Model Builder. 

using System;
using FunctionAppML.Model;

namespace FunctionAppML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                TransactionDate = @"3/05/2021 12:00:00 AM",
                Description = @"Payment to 016-494 340843493 Hillary",
                Debit = 6F,
                Credit = 0F,
                BankStatementId = 6F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Category with predicted Category from sample data...\n\n");
            Console.WriteLine($"TransactionDate: {sampleData.TransactionDate}");
            Console.WriteLine($"Description: {sampleData.Description}");
            Console.WriteLine($"Debit: {sampleData.Debit}");
            Console.WriteLine($"Credit: {sampleData.Credit}");
            Console.WriteLine($"BankStatementId: {sampleData.BankStatementId}");
            Console.WriteLine($"\n\nPredicted Category value {predictionResult.Prediction} \nPredicted Category scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
